import { ItemTypes } from './ItemTypes'

export const initialData = [
  {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_A.ogg',
      wind: 'sound/wind/wind_A.ogg',
      birds: 'sound/birds/birds_A.ogg',
      beach: 'sound/beach/beach_A.ogg',
      rain: 'sound/rain/rain_A.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_B.ogg',
      wind: 'sound/wind/wind_B.ogg',
      birds: 'sound/birds/birds_B.ogg',
      beach: 'sound/beach/beach_B.ogg',
      rain: 'sound/rain/rain_B.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_C.ogg',
      wind: 'sound/wind/wind_C.ogg',
      birds: 'sound/birds/birds_C.ogg',
      beach: 'sound/beach/beach_C.ogg',
      rain: 'sound/rain/rain_C.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_D.ogg',
      wind: 'sound/wind/wind_D.ogg',
      birds: 'sound/birds/birds_D.ogg',
      beach: 'sound/beach/beach_D.ogg',
      rain: 'sound/rain/rain_D.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_A.ogg',
      wind: 'sound/wind/wind_A.ogg',
      birds: 'sound/birds/birds_A.ogg',
      beach: 'sound/beach/beach_A.ogg',
      rain: 'sound/rain/rain_A.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_B.ogg',
      wind: 'sound/wind/wind_B.ogg',
      birds: 'sound/birds/birds_B.ogg',
      beach: 'sound/beach/beach_B.ogg',
      rain: 'sound/rain/rain_B.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_C.ogg',
      wind: 'sound/wind/wind_C.ogg',
      birds: 'sound/birds/birds_C.ogg',
      beach: 'sound/beach/beach_C.ogg',
      rain: 'sound/rain/rain_C.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_D.ogg',
      wind: 'sound/wind/wind_D.ogg',
      birds: 'sound/birds/birds_D.ogg',
      beach: 'sound/beach/beach_D.ogg',
      rain: 'sound/rain/rain_D.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_A.ogg',
      wind: 'sound/wind/wind_A.ogg',
      birds: 'sound/birds/birds_A.ogg',
      beach: 'sound/beach/beach_A.ogg',
      rain: 'sound/rain/rain_A.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_B.ogg',
      wind: 'sound/wind/wind_B.ogg',
      birds: 'sound/birds/birds_B.ogg',
      beach: 'sound/beach/beach_B.ogg',
      rain: 'sound/rain/rain_B.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_C.ogg',
      wind: 'sound/wind/wind_C.ogg',
      birds: 'sound/birds/birds_C.ogg',
      beach: 'sound/beach/beach_C.ogg',
      rain: 'sound/rain/rain_C.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_D.ogg',
      wind: 'sound/wind/wind_D.ogg',
      birds: 'sound/birds/birds_D.ogg',
      beach: 'sound/beach/beach_D.ogg',
      rain: 'sound/rain/rain_D.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_A.ogg',
      wind: 'sound/wind/wind_A.ogg',
      birds: 'sound/birds/birds_A.ogg',
      beach: 'sound/beach/beach_A.ogg',
      rain: 'sound/rain/rain_A.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_B.ogg',
      wind: 'sound/wind/wind_B.ogg',
      birds: 'sound/birds/birds_B.ogg',
      beach: 'sound/beach/beach_B.ogg',
      rain: 'sound/rain/rain_B.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_C.ogg',
      wind: 'sound/wind/wind_C.ogg',
      birds: 'sound/birds/birds_C.ogg',
      beach: 'sound/beach/beach_C.ogg',
      rain: 'sound/rain/rain_C.ogg',
    },
    type: "",
    volume: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    audioSrc: {
      fire: 'sound/fire/fire_D.ogg',
      wind: 'sound/wind/wind_D.ogg',
      birds: 'sound/birds/birds_D.ogg',
      beach: 'sound/beach/beach_D.ogg',
      rain: 'sound/rain/rain_D.ogg',
    },
    type: "",
    volume: 0,
  },
]
