import { ItemTypes } from './ItemTypes'

export const initialData = [
  {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  },
]
