import { ItemTypes } from '../types/ItemTypes'

export const initialData = [
  {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  },
]

export const beachCampfire = [
  {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: 'Fire',
    file: ['sound/fire/fire_A.ogg', 'sound/fire/fire_B.ogg', 'sound/fire/fire_C.ogg', 'sound/fire/fire_D.ogg'],
    type: ItemTypes.FIRE,
    volume: 4,
    complexity: 1,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: 'Birds',
    file: ['sound/birds/birds_A.ogg', 'sound/birds/birds_B.ogg', 'sound/birds/birds_C.ogg', 'sound/birds/birds_D.ogg'],
    type: ItemTypes.BIRDS,
    volume: 3,
    complexity: 2,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: 'Beach',
    file: ['sound/beach/beach_A.ogg', 'sound/beach/beach_B.ogg', 'sound/beach/beach_C.ogg', 'sound/beach/beach_D.ogg'],
    type: ItemTypes.BEACH,
    volume: 2,
    complexity: 3,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  },
]

export const heavyRain = [
  {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: 'Rain',
    file: ['sound/rain/rain_A.ogg', 'sound/rain/rain_B.ogg', 'sound/rain/rain_C.ogg', 'sound/rain/rain_D.ogg'],
    type: ItemTypes.RAIN,
    volume: 4,
    complexity: 4,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: 'Rain',
    file: ['sound/rain/rain_A.ogg', 'sound/rain/rain_B.ogg', 'sound/rain/rain_C.ogg', 'sound/rain/rain_D.ogg'],
    type: ItemTypes.RAIN,
    volume: 3,
    complexity: 3,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: 'Rain',
    file: ['sound/rain/rain_A.ogg', 'sound/rain/rain_B.ogg', 'sound/rain/rain_C.ogg', 'sound/rain/rain_D.ogg'],
    type: ItemTypes.RAIN,
    volume: 2,
    complexity: 2,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: 'Rain',
    file: ['sound/rain/rain_A.ogg', 'sound/rain/rain_B.ogg', 'sound/rain/rain_C.ogg', 'sound/rain/rain_D.ogg'],
    type: ItemTypes.RAIN,
    volume: 1,
    complexity: 1,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  }, {
    accepts: [ItemTypes.FIRE, ItemTypes.BIRDS, ItemTypes.BEACH, ItemTypes.RAIN, ItemTypes.WIND],
    lastDroppedItem: null,
    file: null,
    type: null,
    volume: 0,
    complexity: 0,
  },
]
